In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
list = arr.tolist()
print(arr)
print(list)



[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [3]:
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
print("Numpy Matrix is:")
print(n_array)

diag = np.diagonal(n_array)
print(diag)
print(sum(diag))

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]
[55 44 77]
176


In [11]:
import numpy as np
a = [[1,2],[3,5]]
print(a.shape())

x=int(input())
for (i,y) in a.shape():
    print (a[a>2])



AttributeError: 'list' object has no attribute 'shape'

In [13]:
import numpy as np

a= np.array([10, 20, 30, 40, 50])
b = np.array([50, 50, 50, 50, 50])

c = a + b
print("c=",c)


c= [ 60  70  80  90 100]
